# Generated by Django 4.0.4 on 2022-05-21 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='f_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='fname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='l_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='lname'),
        ),
    ]
