# Generated by Django 4.0.4 on 2022-05-21 13:58

import datetime
import django.core.validators
from django.db import migrations, models
import core.validators
import teachers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='fname')),
                ('age', models.PositiveIntegerField()),
                ('teacher_last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='lname')),
                ('birthday', models.DateField(default=datetime.date.today, validators=[core.validators.adult_validator])),
                ('phone_number', models.CharField(max_length=25, null=True, validators=[teachers.validators.phone_number_validator, teachers.validators.phone_number_norm])),
            ],
        ),
    ]
