# Generated by Django 4.0.4 on 2022-05-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
