# Generated by Django 4.0.4 on 2022-05-21 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_first_name',
            field=models.CharField(db_column='t_f_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='fname'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_last_name',
            field=models.CharField(db_column='t_l_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='lname'),
        ),
    ]
